= Pivotal Cloud Foundry Workshop @ T

== Schedule

This workshop will provide developers and operators an in-depth overview of Pivotal Cloud Foundry concepts, architecture and fundamentals of pushing code and building applications. The session includes presentations, demos and hands-on labs;

8:00 AM -   9:00 AM::   Registration & Breakfast
9:00 AM -  10:00 AM::   Cloud Native for Enterprise | Rapidly Delivering Continuous Value for the Business
10:00 AM - 10:30 AM::   Platform as a Service Defined 
10:30 AM - 11:00 AM::   Cloud Foundry Overview
11:00 AM - 11:15 AM::   Break
11:15 AM - 12:15 PM:: .NET Developer Focused Cloud Foundry Workshop

12:15 PM - 12:45 PM:: Lunch Break

12:45 PM - 4:30 PM::   .NET Developer Focused Cloud Foundry Workshop
  * From Zero to Pushing your first .NET Applications to Pivotal Cloud Foundry

  * Scaling Applications

  * Monitoring Applications

  * Updating Applications (blue-green updates)

  * Binding Applications to Dependencies

  * Cloud Foundry Roles / Responsibilities (App Developer, App Operator, Platform Developer, Platform Operator)
 
  * Q&A

  * Pivotal Cloud Foundry for Operators Demonstration: (Ops Manager/Apps Manager)

  * Q&A and Next Steps (3:30 PM - 4:00 PM)  


== Workshop Material
** Lab 1 - From Zero to Pushing Your First Application


== Additional Developer Track Course Materials

* Session 1: link:presentations/Session_1_Cloud_Native_Enterprise.pptx[Welcome to the Cloud Native Enterprise (PowerPoint download)]
* Session 2: link:presentations/Session_2_Architecture_And_Operations.pptx[Pivotal Cloud Foundry Architecture and Operations (PowerPoint download)]
* Session 3: link:presentations/Session_3_Services_Overview.pptx[Pivotal Cloud Foundry Services (PowerPoint download)]
** link:labs/lab2/lab.adoc[Lab 2 - Binding to Cloud Foundry Services]
** link:labs/lab3/lab.adoc[Lab 3 - Operating Your Application]
** link:labs/lab4/lab.adoc[Lab 4 - Monitoring Your Application]

* Session Presentation: link:presentations/PCF_Overview_and_Ops_Workshop.pptx[Pivotal Cloud Foundry Operator Focused Session/Presentation]
